//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ISSUEBOOK
    {
        public int ISSUECODE { get; set; }
        public int MEMBERCODE { get; set; }
        public int BOOKCODE { get; set; }
        public System.DateTime ISSUEDATE { get; set; }
        public System.DateTime DUEDATE { get; set; }
        public Nullable<System.DateTime> RETURNDATE { get; set; }
    
        public virtual BOOK BOOK { get; set; }
        public virtual MEMBER MEMBER { get; set; }
    }
}
