//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEMBER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MEMBER()
        {
            this.ISSUEBOOKs = new HashSet<ISSUEBOOK>();
        }
    
        public int MEMBERCODE { get; set; }
        public string MEMBERNAME { get; set; }
        public int MEMBERTYPEID { get; set; }
        public Nullable<int> NO_OF_BOOKISSUED { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ISSUEBOOK> ISSUEBOOKs { get; set; }
        public virtual MEMBERTYPE MEMBERTYPE { get; set; }
    }
}
